version: '3.8'

services:
  # Backend API Service
  backend:
    build:
      context: ./agentverse_api
      dockerfile: Dockerfile
    container_name: agentverse-backend
    ports:
      - "8000:8000"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./src:/app/src
      - ./config:/app/config
    depends_on:
      - redis
    networks:
      - agentverse-network

  # Frontend UI Service
  frontend:
    build:
      context: ./agentverse_ui
      dockerfile: Dockerfile
    container_name: agentverse-frontend
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - agentverse-network

  # Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: agentverse-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - agentverse-network

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: agentverse-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - agentverse-network

networks:
  agentverse-network:
    driver: bridge

volumes:
  redis-data: